# Импортирование библиотеки Numpy

In [1]:
import numpy as np

# Примеры создания массивов

## Обычные списки 

In [2]:
a = [3,3,3]
print([i+3 for i in a])

# print(a+3) Одна из ключевых преимуществ Numpy над обычными "питоновскими" списками 


[6, 6, 6]


In [3]:
a = [1,2,3]
print(a,'-',type(a))

a_np = np.array(a)
print(a_np,'-',type(a_np))

print(a_np+3)


[1, 2, 3] - <class 'list'>
[1 2 3] - <class 'numpy.ndarray'>
[4 5 6]


## Списки Numpy и функции для создания n-мерных векторов\тензоров с помощью `np.zeros()`, `np.ones()`, `np.arange()`

In [4]:
np.zeros([4,1])

array([[0.],
       [0.],
       [0.],
       [0.]])

In [5]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.ones([5,1])*np.zeros([1,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.arange(1,100,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [8]:
np.ones([5,1])*np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Демонстрация атрибутов

In [9]:
ab = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(ab.dtype,ab.shape)

b = np.array([[1],[2],[3],[5]],dtype=float)
print(b.dtype, b.shape)
 
a = np.array([1,1,1,1],dtype=int)
print(a.dtype,a.shape)

int64 (3, 3)
float64 (4, 1)
int64 (4,)


# Примеры индексирования и срезов

In [10]:
ind = np.array([1,2,4,8,16])
print('ind[::-1]','-',ind[::-1])

print('ind[:3]','-',ind[:3])

indn = np.eye(5)
indn[(2,2)] = 3

print('indn -\n',indn)


ind[::-1] - [16  8  4  2  1]
ind[:3] - [1 2 4]
indn -
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Получение отдельного элемента

In [11]:
d = np.array([[10,11,12,13],
             [14,15,16,17],
             [18,19,20,21],
             [22,23,24,25]
             ])


d[...,3]

array([13, 17, 21, 25])

In [12]:
print(d[::-1],'\n')
d[::-1,::-1]


[[22 23 24 25]
 [18 19 20 21]
 [14 15 16 17]
 [10 11 12 13]] 



array([[25, 24, 23, 22],
       [21, 20, 19, 18],
       [17, 16, 15, 14],
       [13, 12, 11, 10]])

In [13]:
print(d[...,::-1])

print('\n',d[::-1,::-1])
d.transpose()

[[13 12 11 10]
 [17 16 15 14]
 [21 20 19 18]
 [25 24 23 22]]

 [[25 24 23 22]
 [21 20 19 18]
 [17 16 15 14]
 [13 12 11 10]]


array([[10, 14, 18, 22],
       [11, 15, 19, 23],
       [12, 16, 20, 24],
       [13, 17, 21, 25]])

## Извлечение подмассивов с помощью срезов

In [14]:
trans = d.copy()
tmp = np.empty(trans.shape)
for i in range(4):

    tmp[i,:] = d[...,i]
tmp

array([[10., 14., 18., 22.],
       [11., 15., 19., 23.],
       [12., 16., 20., 24.],
       [13., 17., 21., 25.]])

# Примеры векторных операций и базовых статистик:

In [15]:
# ax^2 + bx + c = 0
x = np.array([6,2,5,1,7])
y = np.array([52,16,40,12,66])

# МНК для полинома 2-й степени
# Обучение модели
A = np.array([[np.float64(len(x)), sum(x), sum(x**2)],
       [sum(x), sum(x**2), sum(x**3)],
       [sum(x**2), sum(x**3), sum(x**4)]],dtype=float)

B = np.array([sum(y),sum(y*x),sum(x**2*y)]).reshape((3,1))

weights = np.linalg.solve(A,B).ravel()
print('Веса модели (Коэффициенты полиномиальной регрессии): ', weights)

y_pred = x**2*weights[2]+ x*weights[1] + weights[0] 

MAE = sum(y - y_pred) / len(x)
print('Средняя абсолютная ошибка:', MAE)

Веса модели (Коэффициенты полиномиальной регрессии):  [10.  1.  1.]
Средняя абсолютная ошибка: 4.973799150320701e-15


Попытка №2. Примеры операций с массивами, простые вычисления/статистик (mean/sum и т.п)

In [18]:
u = np.array([1,2,1,2,2,1,1])
umean = np.mean(u)
usum = np.sum(u)
umedian = np.median(u)
print(f'mean u: {umean}')
print(f'sum u: {usum}')
print(f'median u: {umedian}')

mean u: 1.4285714285714286
sum u: 10
median u: 1.0
